// Fill out your copyright notice in the Description page of Project Settings.

#pragma once
#include "NativeGameplayTags.h"

namespace STGamePlayTags
{

	// Input Tags
	TEAMPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Move)
	TEAMPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Look)
	TEAMPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Hold)
	TEAMPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Hold_Run)
	TEAMPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Hold_Aiming)
	TEAMPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Hold_Crunch)
	

	// player Tags
	TEAMPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Runner)
	TEAMPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Tagger)
	

	// Runner Ability Tags
	TEAMPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Runner_Ability_Equip)
	TEAMPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Runner_Ability_UnEquip)
	TEAMPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Runner_Ability_Equip_WaterGun)

	TEAMPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Runner_Ability_Shoot_WaterGun)
	
	// Runner Weapon Tags
	TEAMPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Runner_Weapon_Watergun)


	// Runner Event Tags
	TEAMPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Runner_Event_WaterGunEquip)
	
	
	// Runner Status Tags
	TEAMPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Runner_Status_Running)
	TEAMPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Runner_Status_Aiming)
	TEAMPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Runner_Status_Crouching)
	TEAMPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Runner_Status_Equipping)

	// Tagger Status Tags
	

	// Input Ability
	TEAMPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_QAbility)
	TEAMPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_EAbility)

	// Object Tags
	TEAMPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Object_Actor_Door)
	TEAMPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Object_Actor_WaterGun)
	TEAMPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Object_Actor_Blackboard)
	TEAMPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Object_Actor_Graffiti)

	// Object Ability Tags
	TEAMPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Object_Ability_Splash)
	
	// Event Tags
	TEAMPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_OnSplashHit)
	
}